export type ApiLang = 'es' | 'ru' | 'en';

const T: Record<ApiLang, Record<string, string>> = {
  es: {
    UNAUTHORIZED: 'No autenticado',
    FORBIDDEN: 'No autorizado',
    NOT_FOUND: 'No encontrado',
    VALIDATION_ERROR: 'Datos invalidos',
    CONFLICT: 'Conflicto con el estado actual',
    INTERNAL_ERROR: 'Error interno del servidor',
    RATE_LIMITED: 'Demasiadas solicitudes, espera un momento',
    INVALID_JSON: 'JSON invalido',
    INVALID_CODE_FORMAT: 'El codigo debe tener exactamente 6 digitos',
    CODE_MUST_DIFFER: 'El nuevo codigo debe ser distinto al actual',
    CODE_IS_DEFAULT: 'No puedes usar 000000 como codigo',
    USER_ALREADY_EXISTS: 'Ya existe un usuario con ese ID',
    USER_NOT_FOUND: 'Usuario no encontrado',
    ROLE_NOT_FOUND: 'Rol no encontrado',
    ROLE_IN_USE: 'Este rol esta en uso',
    COOLDOWN_ACTIVE: 'Debes esperar antes de reintentar',
    QUIZ_NOT_AVAILABLE: 'Este documento no tiene quiz disponible',
    QUIZ_POOL_INSUFFICIENT: 'Pool de preguntas insuficiente',
    QUIZ_SESSION_INVALID: 'Sesion expirada o invalida',
    QUIZ_SESSION_WRONG_USER: 'Sesion de otro usuario',
    QUIZ_ANSWERS_MISMATCH: 'Numero de respuestas no coincide',
    SECTION_ACCESS_DENIED: 'No tienes acceso a esta seccion',
    ACCOUNT_DISABLED: 'Cuenta desactivada',
    MUST_CHANGE_CODE: 'Debes cambiar tu codigo',
    MISSING_FIELDS: 'Faltan campos requeridos',
    INVALID_ID_FORMAT: 'ID invalido. Solo letras, numeros y guiones (max 50 caracteres)',
    NAME_TOO_LONG: 'Nombre demasiado largo (max 100 caracteres)',
    MESSAGE_TOO_LONG: 'Mensaje demasiado largo (max 1000 caracteres)',
    NAME_REQUIRED: 'Nombre requerido (2-100 caracteres)',
    INVALID_EMAIL: 'Email invalido',
    INVALID_LANG: 'Idioma invalido',
    INVALID_SECTIONS: 'sections debe ser un array de strings',
    INVALID_EXTRA_SECTIONS: 'extraSections debe ser un array de strings',
    INVALID_DOCUMENT_PATH: 'documentPath invalido',
    ONLY_COMPLETED_TRUE: 'Solo se soporta completed: true',
    READ_TOO_FAST: 'Leido demasiado rapido',
    NO_LEARNING_PATH: 'No hay ruta para este rol',
    CANNOT_DELETE_SELF: 'No puedes eliminar tu propio usuario',
    CANNOT_DELETE_ADMIN_ROLE: 'No se puede eliminar el rol de administrador',
    REGISTRATION_NOT_FOUND: 'Solicitud no encontrada',
    REGISTRATION_ALREADY_PROCESSED: 'Esta solicitud ya fue procesada',
    INVALID_ACTION: 'Accion invalida',
    ROLE_ID_REQUIRED: 'roleId requerido para aprobar',
    CERT_NOT_FOUND: 'Certificado no encontrado',
  },
  ru: {
    UNAUTHORIZED: 'Не аутентифицирован',
    FORBIDDEN: 'Нет доступа',
    NOT_FOUND: 'Не найдено',
    VALIDATION_ERROR: 'Неверные данные',
    CONFLICT: 'Конфликт с текущим состоянием',
    INTERNAL_ERROR: 'Внутренняя ошибка сервера',
    RATE_LIMITED: 'Слишком много запросов, подождите',
    INVALID_JSON: 'Некорректный JSON',
    INVALID_CODE_FORMAT: 'Код должен состоять ровно из 6 цифр',
    CODE_MUST_DIFFER: 'Новый код должен отличаться от текущего',
    CODE_IS_DEFAULT: 'Нельзя использовать 000000 в качестве кода',
    USER_ALREADY_EXISTS: 'Пользователь с таким ID уже существует',
    USER_NOT_FOUND: 'Пользователь не найден',
    ROLE_NOT_FOUND: 'Роль не найдена',
    ROLE_IN_USE: 'Эта роль используется',
    COOLDOWN_ACTIVE: 'Подождите перед повторной попыткой',
    QUIZ_NOT_AVAILABLE: 'Для этого документа нет доступного теста',
    QUIZ_POOL_INSUFFICIENT: 'Недостаточно вопросов в пуле',
    QUIZ_SESSION_INVALID: 'Сессия истекла или недействительна',
    QUIZ_SESSION_WRONG_USER: 'Сессия другого пользователя',
    QUIZ_ANSWERS_MISMATCH: 'Количество ответов не совпадает',
    SECTION_ACCESS_DENIED: 'У вас нет доступа к этому разделу',
    ACCOUNT_DISABLED: 'Аккаунт отключен',
    MUST_CHANGE_CODE: 'Необходимо изменить код',
    MISSING_FIELDS: 'Отсутствуют обязательные поля',
    INVALID_ID_FORMAT: 'Некорректный ID. Только буквы, цифры и дефисы (макс. 50 символов)',
    NAME_TOO_LONG: 'Слишком длинное имя (макс. 100 символов)',
    MESSAGE_TOO_LONG: 'Слишком длинное сообщение (макс. 1000 символов)',
    NAME_REQUIRED: 'Имя обязательно (2-100 символов)',
    INVALID_EMAIL: 'Некорректный email',
    INVALID_LANG: 'Некорректный язык',
    INVALID_SECTIONS: 'sections должен быть массивом строк',
    INVALID_EXTRA_SECTIONS: 'extraSections должен быть массивом строк',
    INVALID_DOCUMENT_PATH: 'Некорректный documentPath',
    ONLY_COMPLETED_TRUE: 'Поддерживается только completed: true',
    READ_TOO_FAST: 'Прочитано слишком быстро',
    NO_LEARNING_PATH: 'Для этой роли нет обучающего маршрута',
    CANNOT_DELETE_SELF: 'Нельзя удалить собственного пользователя',
    CANNOT_DELETE_ADMIN_ROLE: 'Нельзя удалить роль администратора',
    REGISTRATION_NOT_FOUND: 'Заявка не найдена',
    REGISTRATION_ALREADY_PROCESSED: 'Эта заявка уже обработана',
    INVALID_ACTION: 'Недопустимое действие',
    ROLE_ID_REQUIRED: 'Требуется roleId для одобрения',
    CERT_NOT_FOUND: 'Сертификат не найден',
  },
  en: {
    UNAUTHORIZED: 'Not authenticated',
    FORBIDDEN: 'Not authorized',
    NOT_FOUND: 'Not found',
    VALIDATION_ERROR: 'Invalid data',
    CONFLICT: 'Conflict with current state',
    INTERNAL_ERROR: 'Internal server error',
    RATE_LIMITED: 'Too many requests, please wait',
    INVALID_JSON: 'Invalid JSON',
    INVALID_CODE_FORMAT: 'Code must be exactly 6 digits',
    CODE_MUST_DIFFER: 'New code must differ from the current one',
    CODE_IS_DEFAULT: 'You cannot use 000000 as a code',
    USER_ALREADY_EXISTS: 'A user with that ID already exists',
    USER_NOT_FOUND: 'User not found',
    ROLE_NOT_FOUND: 'Role not found',
    ROLE_IN_USE: 'This role is in use',
    COOLDOWN_ACTIVE: 'You must wait before retrying',
    QUIZ_NOT_AVAILABLE: 'No quiz available for this document',
    QUIZ_POOL_INSUFFICIENT: 'Question pool too small',
    QUIZ_SESSION_INVALID: 'Session expired or invalid',
    QUIZ_SESSION_WRONG_USER: 'Session belongs to a different user',
    QUIZ_ANSWERS_MISMATCH: 'Answer count does not match',
    SECTION_ACCESS_DENIED: 'You do not have access to this section',
    ACCOUNT_DISABLED: 'Account disabled',
    MUST_CHANGE_CODE: 'You must change your code',
    MISSING_FIELDS: 'Required fields are missing',
    INVALID_ID_FORMAT: 'Invalid ID. Only letters, numbers and dashes (max 50 chars)',
    NAME_TOO_LONG: 'Name too long (max 100 chars)',
    MESSAGE_TOO_LONG: 'Message too long (max 1000 chars)',
    NAME_REQUIRED: 'Name required (2-100 chars)',
    INVALID_EMAIL: 'Invalid email',
    INVALID_LANG: 'Invalid language',
    INVALID_SECTIONS: 'sections must be an array of strings',
    INVALID_EXTRA_SECTIONS: 'extraSections must be an array of strings',
    INVALID_DOCUMENT_PATH: 'Invalid documentPath',
    ONLY_COMPLETED_TRUE: 'Only completed: true is supported',
    READ_TOO_FAST: 'Marked as read too fast',
    NO_LEARNING_PATH: 'No learning path for this role',
    CANNOT_DELETE_SELF: 'You cannot delete your own user',
    CANNOT_DELETE_ADMIN_ROLE: 'The admin role cannot be deleted',
    REGISTRATION_NOT_FOUND: 'Registration not found',
    REGISTRATION_ALREADY_PROCESSED: 'This registration was already processed',
    INVALID_ACTION: 'Invalid action',
    ROLE_ID_REQUIRED: 'roleId required for approval',
    CERT_NOT_FOUND: 'Certificate not found',
  },
};

export function translateApiError(
  body: { error?: string; code?: string } | null,
  lang: ApiLang,
  fallback = 'An error occurred'
): string {
  if (!body) return fallback;
  if (body.code && T[lang]?.[body.code]) return T[lang][body.code];
  return body.error || fallback;
}
